services:
  app:
    image: todo-frontend-dev
    volumes:
      - ./todo-frontend:/usr/src/app
    ports:
      - 5173:5173
  nginx:
    image: nginx:1.29
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - app
